/**
 * @author jquinlan
 */
import java.io.*;
public class Homework4UI extends javax.swing.JFrame {
    Product productGUI = new Product();
    /**
     * Creates new form Homework4UI_2
     */
    public Homework4UI() {
        Homework4.inputUserName(productGUI);
        
        initComponents();
        printScreenGUI(productGUI);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameFieldAdd = new javax.swing.JTextField();
        codeFieldAdd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        descriptFieldAdd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        priceFieldAdd = new javax.swing.JTextField();
        quantityFieldAdd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        descriptDisplay9 = new javax.swing.JFormattedTextField();
        quantityDisplay9 = new javax.swing.JFormattedTextField();
        quantityDisplay8 = new javax.swing.JFormattedTextField();
        priceDisplay8 = new javax.swing.JFormattedTextField();
        descriptDisplay8 = new javax.swing.JFormattedTextField();
        codeDisplay8 = new javax.swing.JFormattedTextField();
        codeDisplay7 = new javax.swing.JFormattedTextField();
        priceDisplay2 = new javax.swing.JFormattedTextField();
        quantityDisplay2 = new javax.swing.JFormattedTextField();
        descriptDisplay3 = new javax.swing.JFormattedTextField();
        codeDisplay2 = new javax.swing.JFormattedTextField();
        descriptDisplay2 = new javax.swing.JFormattedTextField();
        descriptDisplay10 = new javax.swing.JFormattedTextField();
        quantityDisplay3 = new javax.swing.JFormattedTextField();
        codeDisplay10 = new javax.swing.JFormattedTextField();
        priceDisplay9 = new javax.swing.JFormattedTextField();
        priceDisplay10 = new javax.swing.JFormattedTextField();
        quantityDisplay10 = new javax.swing.JFormattedTextField();
        codeDisplay9 = new javax.swing.JFormattedTextField();
        codeDisplay1 = new javax.swing.JFormattedTextField();
        descriptDisplay1 = new javax.swing.JFormattedTextField();
        priceDisplay1 = new javax.swing.JFormattedTextField();
        quantityDisplay1 = new javax.swing.JFormattedTextField();
        quantityDisplay4 = new javax.swing.JFormattedTextField();
        priceDisplay4 = new javax.swing.JFormattedTextField();
        descriptDisplay4 = new javax.swing.JFormattedTextField();
        quantityDisplay5 = new javax.swing.JFormattedTextField();
        codeDisplay4 = new javax.swing.JFormattedTextField();
        descriptDisplay5 = new javax.swing.JFormattedTextField();
        priceDisplay3 = new javax.swing.JFormattedTextField();
        codeDisplay3 = new javax.swing.JFormattedTextField();
        descriptDisplay6 = new javax.swing.JFormattedTextField();
        priceDisplay6 = new javax.swing.JFormattedTextField();
        quantityDisplay6 = new javax.swing.JFormattedTextField();
        codeDisplay6 = new javax.swing.JFormattedTextField();
        quantityDisplay7 = new javax.swing.JFormattedTextField();
        priceDisplay7 = new javax.swing.JFormattedTextField();
        descriptDisplay7 = new javax.swing.JFormattedTextField();
        priceDisplay5 = new javax.swing.JFormattedTextField();
        codeDisplay5 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        totalDisplay = new javax.swing.JFormattedTextField();
        nameDisplay1 = new javax.swing.JTextField();
        nameDisplay2 = new javax.swing.JTextField();
        nameDisplay3 = new javax.swing.JTextField();
        nameDisplay4 = new javax.swing.JTextField();
        nameDisplay5 = new javax.swing.JTextField();
        nameDisplay6 = new javax.swing.JTextField();
        nameDisplay7 = new javax.swing.JTextField();
        nameDisplay8 = new javax.swing.JTextField();
        nameDisplay9 = new javax.swing.JTextField();
        nameDisplay10 = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        yesRadioFull = new javax.swing.JRadioButton();
        noRadioFull = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        discountDisplay1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        discountDisplay2 = new javax.swing.JTextField();
        discountDisplay3 = new javax.swing.JTextField();
        discountDisplay4 = new javax.swing.JTextField();
        discountDisplay5 = new javax.swing.JTextField();
        discountDisplay6 = new javax.swing.JTextField();
        discountDisplay7 = new javax.swing.JTextField();
        discountDisplay8 = new javax.swing.JTextField();
        discountDisplay9 = new javax.swing.JTextField();
        discountDisplay10 = new javax.swing.JTextField();
        subtotalDisplay1 = new javax.swing.JFormattedTextField();
        subtotalDisplay2 = new javax.swing.JFormattedTextField();
        subtotalDisplay3 = new javax.swing.JFormattedTextField();
        subtotalDisplay4 = new javax.swing.JFormattedTextField();
        subtotalDisplay5 = new javax.swing.JFormattedTextField();
        subtotalDisplay6 = new javax.swing.JFormattedTextField();
        subtotalDisplay7 = new javax.swing.JFormattedTextField();
        subtotalDisplay8 = new javax.swing.JFormattedTextField();
        subtotalDisplay9 = new javax.swing.JFormattedTextField();
        subtotalDisplay10 = new javax.swing.JFormattedTextField();
        taxDisplay = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        displayFirstName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        displayLastName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        displayID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Item"));

        jLabel1.setText("Name");

        jLabel2.setText("Code");

        jLabel3.setText("Description");

        jLabel4.setText("Price");

        jLabel5.setText("Quantity");

        addButton.setText("Add");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(codeFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(priceFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quantityFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Invoice"));

        descriptDisplay9.setEditable(false);

        priceDisplay8.setEditable(false);
        priceDisplay8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));

        descriptDisplay8.setEditable(false);

        codeDisplay8.setEditable(false);

        codeDisplay7.setEditable(false);

        priceDisplay2.setEditable(false);
        priceDisplay2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));

        descriptDisplay3.setEditable(false);

        codeDisplay2.setEditable(false);

        descriptDisplay2.setEditable(false);

        descriptDisplay10.setEditable(false);

        codeDisplay10.setEditable(false);

        priceDisplay9.setEditable(false);
        priceDisplay9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));

        priceDisplay10.setEditable(false);
        priceDisplay10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));

        codeDisplay9.setEditable(false);

        codeDisplay1.setEditable(false);

        descriptDisplay1.setEditable(false);

        priceDisplay1.setEditable(false);
        priceDisplay1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));

        priceDisplay4.setEditable(false);
        priceDisplay4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));

        descriptDisplay4.setEditable(false);

        codeDisplay4.setEditable(false);

        descriptDisplay5.setEditable(false);

        priceDisplay3.setEditable(false);
        priceDisplay3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));

        codeDisplay3.setEditable(false);

        descriptDisplay6.setEditable(false);

        priceDisplay6.setEditable(false);
        priceDisplay6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));

        codeDisplay6.setEditable(false);

        priceDisplay7.setEditable(false);
        priceDisplay7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));

        descriptDisplay7.setEditable(false);

        priceDisplay5.setEditable(false);
        priceDisplay5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));

        codeDisplay5.setEditable(false);

        jLabel11.setText("Total");

        totalDisplay.setEditable(false);
        totalDisplay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));

        nameDisplay1.setEditable(false);

        nameDisplay2.setEditable(false);

        nameDisplay3.setEditable(false);

        nameDisplay4.setEditable(false);

        nameDisplay5.setEditable(false);

        nameDisplay6.setEditable(false);

        nameDisplay7.setEditable(false);

        nameDisplay8.setEditable(false);

        nameDisplay9.setEditable(false);

        nameDisplay10.setEditable(false);

        updateButton.setText("Update");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });

        jLabel6.setText("Product Name");

        jLabel7.setText("Code");

        jLabel8.setText("Description");

        jLabel9.setText("Price");

        jLabel10.setText("Quantity");

        jLabel12.setText("Subtotal");

        buttonGroup4.add(yesRadioFull);
        yesRadioFull.setText("Yes");

        buttonGroup4.add(noRadioFull);
        noRadioFull.setText("No");

        jLabel13.setText("Pay in full? (%" + String.valueOf(100.0 * productGUI.FULLPAY) + " discount!)");

        discountDisplay1.setEditable(false);

        jLabel14.setText("Discount?");

        discountDisplay2.setEditable(false);

        discountDisplay3.setEditable(false);

        discountDisplay4.setEditable(false);

        discountDisplay5.setEditable(false);

        discountDisplay6.setEditable(false);

        discountDisplay7.setEditable(false);

        discountDisplay8.setEditable(false);

        discountDisplay9.setEditable(false);

        discountDisplay10.setEditable(false);

        subtotalDisplay1.setEditable(false);
        subtotalDisplay1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));
        productGUI.setIndex(0);
        subtotalDisplay1.setValue(productGUI.getPrice() * productGUI.getQuantity());

        subtotalDisplay2.setEditable(false);
        subtotalDisplay2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));
        productGUI.setIndex(1);
        subtotalDisplay2.setValue(productGUI.getPrice() * productGUI.getQuantity());

        subtotalDisplay3.setEditable(false);
        subtotalDisplay3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));
        productGUI.setIndex(2);
        subtotalDisplay3.setValue(productGUI.getPrice() * productGUI.getQuantity());

        subtotalDisplay4.setEditable(false);
        subtotalDisplay4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));
        productGUI.setIndex(3);
        subtotalDisplay4.setValue(productGUI.getPrice() * productGUI.getQuantity());

        subtotalDisplay5.setEditable(false);
        subtotalDisplay5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));
        productGUI.setIndex(4);
        subtotalDisplay5.setValue(productGUI.getPrice() * productGUI.getQuantity());

        subtotalDisplay6.setEditable(false);
        subtotalDisplay6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));
        productGUI.setIndex(5);
        subtotalDisplay6.setValue(productGUI.getPrice() * productGUI.getQuantity());

        subtotalDisplay7.setEditable(false);
        subtotalDisplay7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));
        productGUI.setIndex(6);
        subtotalDisplay7.setValue(productGUI.getPrice() * productGUI.getQuantity());

        subtotalDisplay8.setEditable(false);
        subtotalDisplay8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));
        productGUI.setIndex(7);
        subtotalDisplay8.setValue(productGUI.getPrice() * productGUI.getQuantity());

        subtotalDisplay9.setEditable(false);
        subtotalDisplay9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));
        productGUI.setIndex(8);
        subtotalDisplay9.setValue(productGUI.getPrice() * productGUI.getQuantity());

        subtotalDisplay10.setEditable(false);
        subtotalDisplay10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));
        productGUI.setIndex(9);
        subtotalDisplay10.setValue(productGUI.getPrice() * productGUI.getQuantity());

        taxDisplay.setEditable(false);
        taxDisplay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤###0.00;(¤###0.00)"))));
        taxDisplay.setValue(totalGUI() * (1.0 + productGUI.TAX));

        jLabel15.setText("+ %" + (100.0 * productGUI.TAX) + " tax");

        displayFirstName.setText(productGUI.firstName);
        displayFirstName.setEditable(false);

        jLabel16.setText("First Name");

        displayLastName.setText(productGUI.lastName);
        displayLastName.setEditable(false);

        jLabel17.setText("Last Name");

        displayID.setEditable(false);
        displayID.setText(productGUI.customerID);

        jLabel18.setText("ID Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(displayID)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nameDisplay9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(nameDisplay8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameDisplay7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameDisplay6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameDisplay5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameDisplay4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameDisplay3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameDisplay2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameDisplay10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codeDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptDisplay3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codeDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptDisplay4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codeDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptDisplay5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codeDisplay6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptDisplay6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codeDisplay7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptDisplay7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codeDisplay8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptDisplay8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codeDisplay9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptDisplay9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codeDisplay10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptDisplay10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codeDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nameDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(codeDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(descriptDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(priceDisplay1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(priceDisplay2)
                            .addComponent(priceDisplay3)
                            .addComponent(priceDisplay4)
                            .addComponent(priceDisplay5)
                            .addComponent(priceDisplay6)
                            .addComponent(priceDisplay7)
                            .addComponent(priceDisplay8)
                            .addComponent(priceDisplay9)
                            .addComponent(priceDisplay10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantityDisplay1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                    .addComponent(quantityDisplay2)
                                    .addComponent(quantityDisplay3)
                                    .addComponent(quantityDisplay4)
                                    .addComponent(quantityDisplay5)
                                    .addComponent(quantityDisplay6)
                                    .addComponent(quantityDisplay7)
                                    .addComponent(quantityDisplay8)
                                    .addComponent(quantityDisplay9)
                                    .addComponent(quantityDisplay10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(subtotalDisplay10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(discountDisplay10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(subtotalDisplay9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(discountDisplay9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(subtotalDisplay8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(discountDisplay8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(subtotalDisplay7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(discountDisplay7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(subtotalDisplay6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(discountDisplay6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(subtotalDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(discountDisplay5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(subtotalDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(discountDisplay4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(subtotalDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(discountDisplay3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(subtotalDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(subtotalDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(discountDisplay1)
                                            .addComponent(discountDisplay2))))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 62, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(taxDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yesRadioFull)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noRadioFull)
                                .addGap(12, 12, 12)
                                .addComponent(updateButton)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeDisplay6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptDisplay6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceDisplay6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityDisplay6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDisplay6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountDisplay6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalDisplay6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeDisplay7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptDisplay7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceDisplay7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityDisplay7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDisplay7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountDisplay7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalDisplay7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeDisplay8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptDisplay8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceDisplay8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityDisplay8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDisplay8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountDisplay8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalDisplay8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeDisplay9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptDisplay9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceDisplay9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityDisplay9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDisplay9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountDisplay9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalDisplay9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeDisplay10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptDisplay10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceDisplay10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityDisplay10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDisplay10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountDisplay10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalDisplay10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(yesRadioFull)
                    .addComponent(noRadioFull)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        totalDisplay.setValue(totalGUI());

        saveButton.setText("Save to \"output.txt\"");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        // Increment the product index until there is an empty space in the GUI
        productGUI.setIndex(0);
        while(productGUI.getName() != null)
            productGUI.incIndex();
        // Add item to the list with the information entered by the user
        productGUI.setName(nameFieldAdd.getText());
        productGUI.setCode(codeFieldAdd.getText());
        productGUI.setDescript(descriptFieldAdd.getText());
        // Empty field exception handling
        if(priceFieldAdd.getText().isEmpty() == true)
            productGUI.setPrice(0);
        else
            productGUI.setPrice(Double.valueOf(priceFieldAdd.getText()));
        if(quantityFieldAdd.getText().isEmpty() == true)
            productGUI.setQuantity(0);
        else
            productGUI.setQuantity(Integer.valueOf(quantityFieldAdd.getText()));
        
        totalDisplay.setValue(totalGUI());
        printScreenGUI(productGUI);
    }//GEN-LAST:event_addButtonMouseClicked

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        productGUI.setIndex(0);
        // Parse quantity fields and update subtotal and discount displays.
        for(int i = 0; i < 10; i++) {
            switch(i){
                case 0: productGUI.setQuantity(Integer.valueOf(quantityDisplay1.getText()));
                        if(productGUI.getQuantity() >= 10) {
                            discountDisplay1.setText("%" + (100.0 * productGUI.ORDER_10) + " DISCOUNT");
                            subtotalDisplay1.setValue((1.0 - productGUI.ORDER_10) * (productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        else {
                            discountDisplay1.setText("");
                            subtotalDisplay1.setValue((productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        productGUI.incIndex();
                        break;
                case 1: productGUI.setQuantity(Integer.valueOf(quantityDisplay2.getText()));
                        if(productGUI.getQuantity() >= 10) {
                            discountDisplay2.setText("%" + (100.0 * productGUI.ORDER_10) + " DISCOUNT");
                            subtotalDisplay2.setValue((1.0 - productGUI.ORDER_10) * (productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        else {
                            discountDisplay2.setText("");
                            subtotalDisplay2.setValue((productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        productGUI.incIndex();
                        break;
                case 2: productGUI.setQuantity(Integer.valueOf(quantityDisplay3.getText()));
                        if(productGUI.getQuantity() >= 10) {
                            discountDisplay3.setText("%" + (100.0 * productGUI.ORDER_10) + " DISCOUNT");
                            subtotalDisplay3.setValue((1.0 - productGUI.ORDER_10) * (productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        else {
                            discountDisplay3.setText("");
                            subtotalDisplay3.setValue((productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        productGUI.incIndex();
                        break;
                case 3: productGUI.setQuantity(Integer.valueOf(quantityDisplay4.getText()));
                        if(productGUI.getQuantity() >= 10) {
                            discountDisplay4.setText("%" + (100.0 * productGUI.ORDER_10) + " DISCOUNT");
                            subtotalDisplay4.setValue((1.0 - productGUI.ORDER_10) * (productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        else {
                            discountDisplay4.setText("");
                            subtotalDisplay4.setValue((productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        productGUI.incIndex();
                        break;
                case 4: productGUI.setQuantity(Integer.valueOf(quantityDisplay5.getText()));
                        if(productGUI.getQuantity() >= 10) {
                            discountDisplay5.setText("%" + (100.0 * productGUI.ORDER_10) + " DISCOUNT");
                            subtotalDisplay5.setValue((1.0 - productGUI.ORDER_10) * (productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        else {
                            discountDisplay5.setText("");
                            subtotalDisplay5.setValue((productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        productGUI.incIndex();
                        break;
                case 5: productGUI.setQuantity(Integer.valueOf(quantityDisplay6.getText()));
                        if(productGUI.getQuantity() >= 10) {
                            discountDisplay6.setText("%" + (100.0 * productGUI.ORDER_10) + " DISCOUNT");
                            subtotalDisplay6.setValue((1.0 - productGUI.ORDER_10) * (productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        else {
                            discountDisplay6.setText("");
                            subtotalDisplay6.setValue((productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        productGUI.incIndex();
                        break;
                case 6: productGUI.setQuantity(Integer.valueOf(quantityDisplay7.getText()));
                        if(productGUI.getQuantity() >= 10) {
                            discountDisplay7.setText("%" + (100.0 * productGUI.ORDER_10) + " DISCOUNT");
                            subtotalDisplay7.setValue((1.0 - productGUI.ORDER_10) * (productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        else {
                            discountDisplay7.setText("");
                            subtotalDisplay7.setValue((productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        productGUI.incIndex();
                        break;
                case 7: productGUI.setQuantity(Integer.valueOf(quantityDisplay8.getText()));
                        if(productGUI.getQuantity() >= 10) {
                            discountDisplay8.setText("%" + (100.0 * productGUI.ORDER_10) + " DISCOUNT");
                            subtotalDisplay8.setValue((1.0 - productGUI.ORDER_10) * (productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        else {
                            discountDisplay8.setText("");
                            subtotalDisplay8.setValue((productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        productGUI.incIndex();
                        break;
                case 8: productGUI.setQuantity(Integer.valueOf(quantityDisplay9.getText()));
                        if(productGUI.getQuantity() >= 10) {
                            discountDisplay9.setText("%" + (100.0 * productGUI.ORDER_10) + " DISCOUNT");
                            subtotalDisplay9.setValue((1.0 - productGUI.ORDER_10) * (productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        else {
                            discountDisplay9.setText("");
                            subtotalDisplay9.setValue((productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        productGUI.incIndex();
                        break;
                case 9: productGUI.setQuantity(Integer.valueOf(quantityDisplay10.getText()));
                        if(productGUI.getQuantity() >= 10) {
                            discountDisplay10.setText("%" + (100.0 * productGUI.ORDER_10) + " DISCOUNT");
                            subtotalDisplay10.setValue((1.0 - productGUI.ORDER_10) * (productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        else {
                            discountDisplay10.setText("");
                            subtotalDisplay10.setValue((productGUI.getPrice() * productGUI.getQuantity()));
                        }
                        productGUI.incIndex();
                        break;
            }
            
        }
        printScreenGUI(productGUI);
    }//GEN-LAST:event_updateButtonMouseClicked

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        // Create output text file and write GUI data to it.
        try {
        FileWriter fstream = new FileWriter("output.txt");
        BufferedWriter out = new BufferedWriter(fstream);
        out.write("   |  Product  | Code |      Description      | Price | Quantity | Subtotal |");
        out.newLine();
        productGUI.setIndex(0);
        while(productGUI.getName() != "") {
            out.write(String.format("    %11s", productGUI.getName()) + String.format(" %6s", productGUI.getCode()) +
                    String.format(" %23s", productGUI.getDescript()) + String.format(" $%6.2f", productGUI.getPrice()) +
                    String.format(" %10d", productGUI.getQuantity()));
            if(productGUI.getQuantity() >= 10) {
                out.write(String.format("  $%8.2f",(productGUI.getQuantity() * productGUI.getPrice() * (1.0 - productGUI.ORDER_10))));
                out.write(" (%" + (100.0*productGUI.ORDER_10 + " DISCOUNT)"));
            }
            else
                out.write(String.format("  $%8.2f",(productGUI.getQuantity() * productGUI.getPrice())));
            out.newLine();
            
            productGUI.incIndex();
        }
        out.write("Total");
        out.newLine();
        out.write("-------");
        out.newLine();
        out.write(taxDisplay.getText());
        out.close();
        }catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_saveButtonMouseClicked

    public void printScreenGUI(Product productGUI) {
        // Update GUI display by assigning product data fields to GUI text fields
        productGUI.setIndex(0);
        for(int i = 0; productGUI.getName() != ""; i++) {
            switch(i){
                case 0: nameDisplay1.setText(productGUI.getName());
                        codeDisplay1.setValue(productGUI.getCode());
                        descriptDisplay1.setValue(productGUI.getDescript());
                        priceDisplay1.setValue(productGUI.getPrice());
                        quantityDisplay1.setValue(productGUI.getQuantity());
                        break;
                case 1: nameDisplay2.setText(productGUI.getName());
                        codeDisplay2.setValue(productGUI.getCode());
                        descriptDisplay2.setValue(productGUI.getDescript());
                        priceDisplay2.setValue(productGUI.getPrice());
                        quantityDisplay2.setValue(productGUI.getQuantity());
                        break;
                case 2: nameDisplay3.setText(productGUI.getName());
                        codeDisplay3.setValue(productGUI.getCode());
                        descriptDisplay3.setValue(productGUI.getDescript());
                        priceDisplay3.setValue(productGUI.getPrice());
                        quantityDisplay3.setValue(productGUI.getQuantity());
                        break;
                case 3: nameDisplay4.setText(productGUI.getName());
                        codeDisplay4.setValue(productGUI.getCode());
                        descriptDisplay4.setValue(productGUI.getDescript());
                        priceDisplay4.setValue(productGUI.getPrice());
                        quantityDisplay4.setValue(productGUI.getQuantity());
                        break;
                case 4: nameDisplay5.setText(productGUI.getName());
                        codeDisplay5.setValue(productGUI.getCode());
                        descriptDisplay5.setValue(productGUI.getDescript());
                        priceDisplay5.setValue(productGUI.getPrice());
                        quantityDisplay5.setValue(productGUI.getQuantity());
                        break;
                case 5: nameDisplay6.setText(productGUI.getName());
                        codeDisplay6.setValue(productGUI.getCode());
                        descriptDisplay6.setValue(productGUI.getDescript());
                        priceDisplay6.setValue(productGUI.getPrice());
                        quantityDisplay6.setValue(productGUI.getQuantity());
                        break;
                case 6: nameDisplay7.setText(productGUI.getName());
                        codeDisplay7.setValue(productGUI.getCode());
                        descriptDisplay7.setValue(productGUI.getDescript());
                        priceDisplay7.setValue(productGUI.getPrice());
                        quantityDisplay7.setValue(productGUI.getQuantity());
                        break;
                case 7: nameDisplay8.setText(productGUI.getName());
                        codeDisplay8.setValue(productGUI.getCode());
                        descriptDisplay8.setValue(productGUI.getDescript());
                        priceDisplay8.setValue(productGUI.getPrice());
                        quantityDisplay8.setValue(productGUI.getQuantity());
                        break;
                case 8: nameDisplay9.setText(productGUI.getName());
                        codeDisplay9.setValue(productGUI.getCode());
                        descriptDisplay9.setValue(productGUI.getDescript());
                        priceDisplay9.setValue(productGUI.getPrice());
                        quantityDisplay9.setValue(productGUI.getQuantity());
                        break;
                case 9: nameDisplay10.setText(productGUI.getName());
                        codeDisplay10.setValue(productGUI.getCode());
                        descriptDisplay10.setValue(productGUI.getDescript());
                        priceDisplay10.setValue(productGUI.getPrice());
                        quantityDisplay10.setValue(productGUI.getQuantity());
                        break;
            }
            productGUI.incIndex();
        }
        // Radio buttons for full pay
        if(yesRadioFull.isSelected() == true)
            totalDisplay.setValue((1.0 - productGUI.FULLPAY) * totalGUI());
        else if(yesRadioFull.isSelected() == false)
            totalDisplay.setValue(totalGUI());
        else
            totalDisplay.setValue(totalGUI());
        // Display total after taxes
        taxDisplay.setValue(Double.parseDouble(totalDisplay.getText().substring(1,totalDisplay.getText().length())) * (1.0 + productGUI.TAX));
    }
    
    // Special method for GUI for finding total. (Before modifiers)
    public double totalGUI() {
        double total = 0;
        total += Double.parseDouble(subtotalDisplay1.getText().substring(1,subtotalDisplay1.getText().length()));
        total += Double.parseDouble(subtotalDisplay2.getText().substring(1,subtotalDisplay2.getText().length()));
        total += Double.parseDouble(subtotalDisplay3.getText().substring(1,subtotalDisplay3.getText().length()));
        total += Double.parseDouble(subtotalDisplay4.getText().substring(1,subtotalDisplay4.getText().length()));
        total += Double.parseDouble(subtotalDisplay5.getText().substring(1,subtotalDisplay5.getText().length()));
        total += Double.parseDouble(subtotalDisplay6.getText().substring(1,subtotalDisplay6.getText().length()));
        total += Double.parseDouble(subtotalDisplay7.getText().substring(1,subtotalDisplay7.getText().length()));
        total += Double.parseDouble(subtotalDisplay8.getText().substring(1,subtotalDisplay8.getText().length()));
        total += Double.parseDouble(subtotalDisplay9.getText().substring(1,subtotalDisplay9.getText().length()));
        total += Double.parseDouble(subtotalDisplay10.getText().substring(1,subtotalDisplay10.getText().length()));
        return total;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homework4UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homework4UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homework4UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homework4UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homework4UI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JFormattedTextField codeDisplay1;
    private javax.swing.JFormattedTextField codeDisplay10;
    private javax.swing.JFormattedTextField codeDisplay2;
    private javax.swing.JFormattedTextField codeDisplay3;
    private javax.swing.JFormattedTextField codeDisplay4;
    private javax.swing.JFormattedTextField codeDisplay5;
    private javax.swing.JFormattedTextField codeDisplay6;
    private javax.swing.JFormattedTextField codeDisplay7;
    private javax.swing.JFormattedTextField codeDisplay8;
    private javax.swing.JFormattedTextField codeDisplay9;
    private javax.swing.JTextField codeFieldAdd;
    private javax.swing.JFormattedTextField descriptDisplay1;
    private javax.swing.JFormattedTextField descriptDisplay10;
    private javax.swing.JFormattedTextField descriptDisplay2;
    private javax.swing.JFormattedTextField descriptDisplay3;
    private javax.swing.JFormattedTextField descriptDisplay4;
    private javax.swing.JFormattedTextField descriptDisplay5;
    private javax.swing.JFormattedTextField descriptDisplay6;
    private javax.swing.JFormattedTextField descriptDisplay7;
    private javax.swing.JFormattedTextField descriptDisplay8;
    private javax.swing.JFormattedTextField descriptDisplay9;
    private javax.swing.JTextField descriptFieldAdd;
    private javax.swing.JTextField discountDisplay1;
    private javax.swing.JTextField discountDisplay10;
    private javax.swing.JTextField discountDisplay2;
    private javax.swing.JTextField discountDisplay3;
    private javax.swing.JTextField discountDisplay4;
    private javax.swing.JTextField discountDisplay5;
    private javax.swing.JTextField discountDisplay6;
    private javax.swing.JTextField discountDisplay7;
    private javax.swing.JTextField discountDisplay8;
    private javax.swing.JTextField discountDisplay9;
    private javax.swing.JTextField displayFirstName;
    private javax.swing.JTextField displayID;
    private javax.swing.JTextField displayLastName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nameDisplay1;
    private javax.swing.JTextField nameDisplay10;
    private javax.swing.JTextField nameDisplay2;
    private javax.swing.JTextField nameDisplay3;
    private javax.swing.JTextField nameDisplay4;
    private javax.swing.JTextField nameDisplay5;
    private javax.swing.JTextField nameDisplay6;
    private javax.swing.JTextField nameDisplay7;
    private javax.swing.JTextField nameDisplay8;
    private javax.swing.JTextField nameDisplay9;
    private javax.swing.JTextField nameFieldAdd;
    private javax.swing.JRadioButton noRadioFull;
    private javax.swing.JFormattedTextField priceDisplay1;
    private javax.swing.JFormattedTextField priceDisplay10;
    private javax.swing.JFormattedTextField priceDisplay2;
    private javax.swing.JFormattedTextField priceDisplay3;
    private javax.swing.JFormattedTextField priceDisplay4;
    private javax.swing.JFormattedTextField priceDisplay5;
    private javax.swing.JFormattedTextField priceDisplay6;
    private javax.swing.JFormattedTextField priceDisplay7;
    private javax.swing.JFormattedTextField priceDisplay8;
    private javax.swing.JFormattedTextField priceDisplay9;
    private javax.swing.JTextField priceFieldAdd;
    private javax.swing.JFormattedTextField quantityDisplay1;
    private javax.swing.JFormattedTextField quantityDisplay10;
    private javax.swing.JFormattedTextField quantityDisplay2;
    private javax.swing.JFormattedTextField quantityDisplay3;
    private javax.swing.JFormattedTextField quantityDisplay4;
    private javax.swing.JFormattedTextField quantityDisplay5;
    private javax.swing.JFormattedTextField quantityDisplay6;
    private javax.swing.JFormattedTextField quantityDisplay7;
    private javax.swing.JFormattedTextField quantityDisplay8;
    private javax.swing.JFormattedTextField quantityDisplay9;
    private javax.swing.JTextField quantityFieldAdd;
    private javax.swing.JButton saveButton;
    private javax.swing.JFormattedTextField subtotalDisplay1;
    private javax.swing.JFormattedTextField subtotalDisplay10;
    private javax.swing.JFormattedTextField subtotalDisplay2;
    private javax.swing.JFormattedTextField subtotalDisplay3;
    private javax.swing.JFormattedTextField subtotalDisplay4;
    private javax.swing.JFormattedTextField subtotalDisplay5;
    private javax.swing.JFormattedTextField subtotalDisplay6;
    private javax.swing.JFormattedTextField subtotalDisplay7;
    private javax.swing.JFormattedTextField subtotalDisplay8;
    private javax.swing.JFormattedTextField subtotalDisplay9;
    private javax.swing.JFormattedTextField taxDisplay;
    private javax.swing.JFormattedTextField totalDisplay;
    private javax.swing.JButton updateButton;
    private javax.swing.JRadioButton yesRadioFull;
    // End of variables declaration//GEN-END:variables
}
